name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.x'

      - name: Install dependencies
        run: npm ci

      - name: Write variable to .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000/'
          runTests: npm run cy:hl
